spring:
  application:
    name: inactive-user-archiver

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  batch:
    jdbc:
      initialize-schema: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  h2:
    console:
      enabled: true

  profiles:
    active: dev

server:
  port: 8085

