spring:
  datasource:
    url: jdbc:h2:file:/data/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS Schema

  h2:
    console:
      settings:
        web-allow-others: true

