spring:
  datasource:
    url: jdbc:h2:file:/data/testdb;AUTO_SERVER=TRUE;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS Schema
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  sql:
    init:
      mode: always
      schema-locations: file:/app/resources/schema.sql
      data-locations: file:/app/resources/data.sql

  batch:
    jdbc:
      initialize-schema: always  # ou 'always' si tu ne veux pas gérer schema.sql manuellement
